"""Add merge logs

Revision ID: 111bbc2cbd34
Revises: 8c979564d844
Create Date: 2026-03-12 22:44:00.503964

"""

from collections.abc import Sequence

import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "111bbc2cbd34"
down_revision: str | Sequence[str] | None = "8c979564d844"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("receipts", schema=None) as batch_op:
        batch_op.alter_column(
            "status",
            existing_type=sa.VARCHAR(),
            nullable=True,
            existing_server_default=sa.text("'completed'"),
        )

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("receipts", schema=None) as batch_op:
        batch_op.alter_column(
            "status",
            existing_type=sa.VARCHAR(),
            nullable=False,
            existing_server_default=sa.text("'completed'"),
        )

    # ### end Alembic commands ###
