"""add_image_path_v2

Revision ID: 12d2ac6e4a53
Revises: 463f0047cf21
Create Date: 2026-05-13 13:03:52.903768

"""

from collections.abc import Sequence

import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "12d2ac6e4a53"
down_revision: str | Sequence[str] | None = "463f0047cf21"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # Get existing columns to avoid OperationalError
    conn = op.get_bind()
    insp = sa.inspect(conn)
    cols = [c["name"] for c in insp.get_columns("items")]

    with op.batch_alter_table("items", schema=None) as batch_op:
        if "image_path" not in cols:
            batch_op.add_column(sa.Column("image_path", sa.String(), nullable=True))
        else:
            print("Column 'image_path' already present, skipping add.")

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("items", schema=None) as batch_op:
        batch_op.drop_column("image_path")

    # ### end Alembic commands ###
