"""Add nutrition_suggestions table

Revision ID: 321205375fa8
Revises: a2e6c8f1d905
Create Date: 2026-10-05 21:32:58.759158

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import sqlite

# revision identifiers, used by Alembic.
revision: str = '321205375fa8'
down_revision: Union[str, Sequence[str], None] = 'a2e6c8f1d905'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('nutrition_suggestions',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('item_id', sa.Integer(), nullable=False),
    sa.Column('fdc_id', sa.Integer(), nullable=False),
    sa.Column('fdc_description', sa.String(), nullable=False),
    sa.Column('fdc_brand', sa.String(), nullable=True),
    sa.Column('match_score', sa.Float(), nullable=False),
    sa.Column('nutrients', sqlite.JSON(), nullable=False),
    sa.Column('status', sa.String(), nullable=False),
    sa.Column('batch_id', sa.String(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('reviewed_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['item_id'], ['items.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('nutrition_suggestions', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_nutrition_suggestions_batch_id'), ['batch_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_nutrition_suggestions_item_id'), ['item_id'], unique=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('nutrition_suggestions', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_nutrition_suggestions_item_id'))
        batch_op.drop_index(batch_op.f('ix_nutrition_suggestions_batch_id'))

    op.drop_table('nutrition_suggestions')
    # ### end Alembic commands ###
