"""drop_image_path

Revision ID: 463f0047cf21
Revises: aaa29023a7d1
Create Date: 2026-05-13 13:03:00.185955

"""

from collections.abc import Sequence

import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "463f0047cf21"
down_revision: str | Sequence[str] | None = "aaa29023a7d1"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # Get existing columns to avoid KeyError
    conn = op.get_bind()
    insp = sa.inspect(conn)
    cols = [c["name"] for c in insp.get_columns("items")]

    with op.batch_alter_table("items", schema=None) as batch_op:
        if "image_path" in cols:
            batch_op.drop_column("image_path")
        else:
            print("Column 'image_path' already gone or not present, skipping drop.")

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("items", schema=None) as batch_op:
        batch_op.add_column(sa.Column("image_path", sa.VARCHAR(), nullable=True))

    # ### end Alembic commands ###
