"""Add pricing breakdown

Revision ID: 8c979564d844
Revises: 15a2a0898e7f
Create Date: 2026-02-15 21:16:26.467765

"""

from collections.abc import Sequence

import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "8c979564d844"
down_revision: str | Sequence[str] | None = "15a2a0898e7f"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("receipt_items", sa.Column("original_unit_price", sa.Float(), nullable=True))
    op.add_column("receipt_items", sa.Column("total_discount", sa.Float(), nullable=True))

    with op.batch_alter_table("receipt_items") as batch_op:
        batch_op.alter_column(
            "notes", existing_type=sa.VARCHAR(), type_=sa.Text(), existing_nullable=True
        )

    with op.batch_alter_table("receipts") as batch_op:
        # Avoid postgresql.TIMESTAMP and use generic sa.DateTime
        batch_op.alter_column(
            "created_at",
            existing_type=sa.DateTime(),
            type_=sa.DateTime(timezone=True),
            existing_nullable=True,
        )

        # Remove postgres-specific server_default casting for SQLite compatibility
        batch_op.alter_column("status", existing_type=sa.VARCHAR(), nullable=True)

    op.drop_index(op.f("ix_receipts_purchase_date"), table_name="receipts")
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index(op.f("ix_receipts_purchase_date"), "receipts", ["purchase_date"], unique=False)

    with op.batch_alter_table("receipts") as batch_op:
        batch_op.alter_column("status", existing_type=sa.VARCHAR(), nullable=False)
        batch_op.alter_column(
            "created_at",
            existing_type=sa.DateTime(timezone=True),
            type_=sa.DateTime(),
            existing_nullable=True,
        )

    with op.batch_alter_table("receipt_items") as batch_op:
        batch_op.alter_column(
            "notes", existing_type=sa.Text(), type_=sa.VARCHAR(), existing_nullable=True
        )

    op.drop_column("receipt_items", "total_discount")
    op.drop_column("receipt_items", "original_unit_price")
    # ### end Alembic commands ###
