"""add_off_fields_to_item

Revision ID: aaa29023a7d1
Revises: 111bbc2cbd34
Create Date: 2026-05-13 00:36:36.956517

"""

from collections.abc import Sequence

import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "aaa29023a7d1"
down_revision: str | Sequence[str] | None = "111bbc2cbd34"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("items", schema=None) as batch_op:
        batch_op.add_column(sa.Column("off_code", sa.String(), nullable=True))
        batch_op.add_column(sa.Column("image_url", sa.String(), nullable=True))
        batch_op.add_column(sa.Column("nutriscore", sa.String(), nullable=True))
        batch_op.alter_column(
            "gtin", existing_type=sa.TEXT(), type_=sa.String(), existing_nullable=True
        )
        batch_op.alter_column(
            "ingredients", existing_type=sa.TEXT(), type_=sa.String(), existing_nullable=True
        )

    with op.batch_alter_table("receipts", schema=None) as batch_op:
        # Index might not exist in some environments, skipping drop
        # batch_op.drop_index(batch_op.f('ix_receipts_order_number'), sqlite_where=sa.text('order_number IS NOT NULL'))
        batch_op.create_unique_constraint("uq_receipts_order_number", ["order_number"])

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("receipts", schema=None) as batch_op:
        batch_op.drop_constraint("uq_receipts_order_number", type_="unique")
        batch_op.create_index(
            batch_op.f("ix_receipts_order_number"),
            ["order_number"],
            unique=1,
            sqlite_where=sa.text("order_number IS NOT NULL"),
        )

    with op.batch_alter_table("items", schema=None) as batch_op:
        batch_op.alter_column(
            "ingredients", existing_type=sa.String(), type_=sa.TEXT(), existing_nullable=True
        )
        batch_op.alter_column(
            "gtin", existing_type=sa.String(), type_=sa.TEXT(), existing_nullable=True
        )
        batch_op.drop_column("nutriscore")
        batch_op.drop_column("image_url")
        batch_op.drop_column("off_code")

    # ### end Alembic commands ###
